### PR TITLE
xslt fun

### PR DESCRIPTION
**Pull request by nhart**

### CODE REVIEW

**Comment by jordandukart** [comment]
@nhart, does this need to be merged?

**Comment by nhart** [comment]
@jordandukart  yes,  please merge

**Comment by adam-vessey** [comment]
Looking around, and noticed this: Should a ticket be thrown together to track this (so it can be merged for sure), @nhart?

... Doesn't look too crazy, but... is it still necessary?

**Comment by willtp87** [comment]
@nhart  please take a look here.

**Pull request merged**
